Created TF module. Added lambdaAMIBackups.py lambdaAMICleanup.py
cloudposse/terraform-aws-ec2-ami-backup pull request #1
Opened 2017-07-27 18:31 UTC by s2504s

## What
* Created TF module `module tf_lambda_ami_backup`

## Why
* This module contains a terraform configuration that creates two lambda functions
that will take AMI automatic at regular intervals.

2017-07-27 19:05 UTC, osterman requested changes
Can we keep the original filenames? not fond of camelcase filenames for shell scripts.  Also, when renaming files, make sure you use `git mv` so that the diff is cleaner.

2017-07-27 19:08 UTC, osterman commented on backup_function.tf
> +  source_file = "lambdaAMIBackups.py"
use prothon notation (`_`) instead of snakeCase.

2017-08-07 16:16 UTC, comeanother commented on README.md
> +  ami_backups_schedule = "cron(00 19 * * ? *)"
Let's use variables for cron schedule.

2017-08-08 05:51 UTC, osterman commented on README.md
> +  source = "github.com/cloudposse/tf_lambda_ami_backup"
Use precise notation.

2017-08-08 05:53 UTC, osterman commented on backup_function.tf
>  {
Do not use HEREDOC

2017-08-08 05:54 UTC, osterman commented on main.tf
> +  source    = "github.com/cloudposse/tf_label"
Use precise format. Pin version to 0.1.0.

2017-08-08 05:55 UTC, osterman requested changes
See comments

2017-08-08 07:13 UTC, osterman commented on Makefile
> +all: lambda_ami_backups.zip lambda_ami_cleanups.zip
We should add `*.zip` to the `.gitignore`

2017-08-08 07:14 UTC, osterman commented on README.md
> +  ami_backups_schedule = "cron(00 19 * * ? *)"
Normalize spacing

2017-08-08 07:15 UTC, osterman commented on backup_function.tf
>    policy = <<EOF
Do not use HEREDOC

2017-08-08 07:16 UTC, osterman commented on variables.tf
> +variable "ami_backups_schedule" {
Drop `ami_` as it's implied by the name of the module.

2017-08-08 07:16 UTC, osterman commented on variables.tf
> +variable "ami_cleanups_schedule" {
Drop `ami_` as it's implied by the name of the module.

2017-08-08 15:58 UTC, comeanother commented on main.tf
> +  source    = "../tf_label"
Replace `../tf_label` by github source

2017-08-08 16:49 UTC, comeanother commented on main.tf
> +  source    = "git::https://github.com/cloudposse/tf_label.git?ref=0.1.0"
Can we use `git::https://github.com/cloudposse/tf_label?ref=0.1.0`? 
Without `.git`

2017-08-09 22:18 UTC, osterman commented on main.tf
> +  source    = "git::https://github.com/cloudposse/tf_label.git?ref=0.1.0"
i prefer we just standardize around this format:
```
git::https://github.com/cloudposse/tf_label.git?ref=tags/0.1.0
```

Note: be explicit about `tags/` and use the `.git` suffix.

2017-08-09 22:20 UTC, osterman commented on variables.tf
> +variable "backups_schedule" {
lets call it `backup_schedule`

2017-08-09 22:20 UTC, osterman commented on variables.tf
> +variable "cleanups_schedule" {
Lets call it `cleanup_schedule`

2017-08-10 14:11 UTC, comeanother commented on Makefile
> +all: lambda_ami_backups.zip lambda_ami_cleanups.zip
Added

2017-08-10 14:16 UTC, comeanother commented on README.md
> +# Terraform config for automatic AMI create
Replace to `# Terraform module for automatic scheduled AMI creation`

2017-08-10 14:17 UTC, comeanother commented on README.md
> +that will take AMI automatic at regular intervals. It is based on
Replace to `that will create AMI automatically at regular intervals`

2017-08-10 16:06 UTC, osterman commented on backup_function.tf
> +      "ec2:*",
Why are we giving carte blanche access? Please use explicit permissions and not `*`

2017-08-10 16:08 UTC, osterman commented on backup_function.tf
> +  function_name    = "${module.tf_label.id}_backups"
label module by default uses `-` and not `_`. Let's use `-` here.

2017-08-10 16:08 UTC, osterman commented on backup_function.tf
> +  function_name    = "${module.tf_label.id}_cleanups"
lets use `-` here.

2017-08-10 16:09 UTC, osterman commented on backup_function.tf
> +  handler          = "lambda_ami_backups.lambda_handler"
lets use the singular form (`backup`) consistently.

2017-08-10 18:21 UTC, comeanother commented
Let's close this PR in favor of https://github.com/cloudposse/tf_lambda_ami_backup/pull/2.

2017-08-10 18:22 UTC, osterman commented
Closed in favor of https://github.com/cloudposse/tf_lambda_ami_backup/pull/2

2017-08-10 18:22 UTC, closed without merging