apply changes  if a backup schedule has changed
cloudposse/terraform-aws-ec2-ami-backup pull request #5
Opened 2017-08-30 09:59 UTC by SweetOps

## What
* Apply changes  if a backup schedule has changed

## Why
* Changes are not applied by tfami_backup if a backup schedule has changed

2017-08-30 19:38 UTC, osterman submitted a review, later dismissed

2017-08-31 11:11 UTC, const-bon requested changes

2017-08-31 11:11 UTC, comeanother commented on main.tf
> +  schedule_expression = "${null_resource.schedule.triggers.backup}"
`ami_cleanup` should use `cleanup` expression.

2017-08-31 17:42 UTC, osterman approved these changes

2017-09-01 12:26 UTC, const-bon approved these changes

2017-09-01 12:27 UTC, merged